package Mahasiswa;

import Class.*;
import javax.swing.table.DefaultTableModel;
import static Main.MainFrame.ContenPanel;
import org.json.*;

public class pnMahasiswa extends javax.swing.JPanel {

    public pnMahasiswa() {
        initComponents();
        loadTabel();
        loadAngkatan();
        loadProdi();
        cKelas.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cAngkatan = new javax.swing.JComboBox<>();
        cProdi = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMahasiswa = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cKelas = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("BUKU INDUK > MAHASISWA");

        jLabel2.setText("ANGKATAN");

        jLabel3.setText("PRODI");

        cAngkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua" }));
        cAngkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAngkatanActionPerformed(evt);
            }
        });

        cProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua" }));
        cProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cProdiActionPerformed(evt);
            }
        });

        jLabel4.setText("CARI");

        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCariKeyTyped(evt);
            }
        });

        tbMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMahasiswa);

        jLabel5.setText("KELAS");

        cKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(770, 770, 770))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(382, 382, 382)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cAngkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAngkatanActionPerformed
        if (cProdi.getSelectedItem().equals("Semua") && cAngkatan.getSelectedItem().equals("Semua")) {
            loadTabel();
        } else if (!cProdi.getSelectedItem().equals("Semua") && cAngkatan.getSelectedItem().equals("Semua")) {
            Prodi.setProdi(cProdi.getSelectedItem().toString());
            tampilProdi();
        } else if (cProdi.getSelectedItem().equals("Semua") && !cAngkatan.getSelectedItem().equals("Semua")) {
            int semester = Integer.parseInt(cAngkatan.getSelectedItem().toString());
            Angkatan.setAngkatan(semester);
            tampilAngkatan();
        } else if (!cProdi.getSelectedItem().equals("Semua") && !cAngkatan.getSelectedItem().equals("Semua")) {
            int semester = Integer.parseInt(cAngkatan.getSelectedItem().toString());

            mahasiswa.setProdi(cProdi.getSelectedItem().toString());
            mahasiswa.setAngkatan(semester);
            tampilDua();

        }
    }//GEN-LAST:event_cAngkatanActionPerformed

    private void cProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cProdiActionPerformed
        if (cProdi.getSelectedItem().equals("Semua") && cAngkatan.getSelectedItem().equals("Semua")) {
            loadTabel();
        } else if (!cProdi.getSelectedItem().equals("Semua") && cAngkatan.getSelectedItem().equals("Semua")) {
            Prodi.setProdi(cProdi.getSelectedItem().toString());
            tampilProdi();
        } else if (cProdi.getSelectedItem().equals("Semua") && !cAngkatan.getSelectedItem().equals("Semua")) {
            int angkatan = Integer.parseInt(cAngkatan.getSelectedItem().toString());
            Angkatan.setAngkatan(angkatan);
            tampilAngkatan();
        } else if (!cProdi.getSelectedItem().equals("Semua") && !cAngkatan.getSelectedItem().equals("Semua")) {
            int angkatan = Integer.parseInt(cAngkatan.getSelectedItem().toString());

            mahasiswa.setProdi(cProdi.getSelectedItem().toString());
            mahasiswa.setAngkatan(angkatan);
            tampilDua();

        }
    }//GEN-LAST:event_cProdiActionPerformed

    private void tCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyTyped
        mahasiswa.setSearch(tCari.getText());
        tampilSearch();
    }//GEN-LAST:event_tCariKeyTyped

    private void tbMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMahasiswaMouseClicked
        int baris = tbMahasiswa.rowAtPoint(evt.getPoint());
        mahasiswa.setBaris(baris);
        ContenPanel.removeAll();
        ContenPanel.add(new pnProfil());
        ContenPanel.repaint();
        ContenPanel.revalidate();
    }//GEN-LAST:event_tbMahasiswaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cAngkatan;
    private javax.swing.JComboBox<String> cKelas;
    private javax.swing.JComboBox<String> cProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCari;
    private javax.swing.JTable tbMahasiswa;
    // End of variables declaration//GEN-END:variables
    void loadTabel() {

        try {
            mahasiswa mhs = new mahasiswa();
            JSONObject obj = mhs.getMahasiswa();

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nim");
            model.addColumn("Nama");
            model.addColumn("Jenis Kelamin");
            model.addColumn("Angkatan");
            model.addColumn("Prodi");

            int rows = obj.getInt("rows");
            JSONArray results = obj.getJSONArray("results");
            mahasiswa.setDataMhs(results);
            if (rows != 0) {
                for (int i = 0; i < results.length(); i++) {
                    JSONObject item = results.getJSONObject(i);
                    model.addRow(new Object[]{
                        item.getString("mhs_nim"),
                        item.getString("mhs_nama"),
                        item.getString("mhs_jk"),
                        item.getInt("angkatan"),
                        item.getString("prodi")

                    });
                    tbMahasiswa.setModel(model);
                }
            }
        } catch (Exception e) {
        }
    }

    void loadAngkatan() {

        try {
            Angkatan an = new Angkatan();
            JSONObject obj = an.getAngkattan();

            int rows = obj.getInt("rows");
            JSONArray results = obj.getJSONArray("results");
            mahasiswa.setDataMhs(results);
            if (rows != 0) {
                for (int i = 0; i < results.length(); i++) {
                    JSONObject item = results.getJSONObject(i);
                    int angkatan = item.getInt("angkatan");
                    cAngkatan.addItem(String.valueOf(angkatan));

                }

            }
        } catch (Exception e) {
        }

    }

    void loadProdi() {

        try {
            Prodi pd = new Prodi();
            JSONObject obj = pd.getJurusan();

            int rows = obj.getInt("rows");
            JSONArray results = obj.getJSONArray("results");
            mahasiswa.setDataMhs(results);
            if (rows != 0) {
                for (int i = 0; i < results.length(); i++) {
                    JSONObject item = results.getJSONObject(i);
                    String prodi = item.getString("prodi");
                    cProdi.addItem(prodi);

                }

            }
        } catch (Exception e) {
        }

    }

    void tampilAngkatan() {

        try {
            Angkatan an = new Angkatan();
            JSONObject obj = an.tampilAngkatan();

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nim");
            model.addColumn("Nama");
            model.addColumn("Jenis Kelamin");
            model.addColumn("Angkatan");
            model.addColumn("Prodi");

            int rows = obj.getInt("rows");
            JSONArray results = obj.getJSONArray("results");
            mahasiswa.setDataMhs(results);
            if (rows != 0) {
                for (int i = 0; i < results.length(); i++) {
                    JSONObject item = results.getJSONObject(i);
                    model.addRow(new Object[]{
                        item.getString("mhs_nim"),
                        item.getString("mhs_nama"),
                        item.getString("mhs_jk"),
                        item.getInt("angkatan"),
                        item.getString("prodi")

                    });
                    tbMahasiswa.setModel(model);
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    void tampilProdi() {

        try {
            Prodi pd = new Prodi();
            JSONObject obj = pd.tampilJurusan();

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nim");
            model.addColumn("Nama");
            model.addColumn("Jenis Kelamin");
            model.addColumn("Angkatan");
            model.addColumn("Prodi");

            int rows = obj.getInt("rows");
            JSONArray results = obj.getJSONArray("results");
            mahasiswa.setDataMhs(results);
            if (rows != 0) {
                for (int i = 0; i < results.length(); i++) {
                    JSONObject item = results.getJSONObject(i);
                    model.addRow(new Object[]{
                        item.getString("mhs_nim"),
                        item.getString("mhs_nama"),
                        item.getString("mhs_jk"),
                        item.getInt("angkatan"),
                        item.getString("prodi")

                    });
                    tbMahasiswa.setModel(model);
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    void tampilDua() {

        try {
            mahasiswa mhs = new mahasiswa();
            JSONObject obj = mhs.tampilDua();

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nim");
            model.addColumn("Nama");
            model.addColumn("Jenis Kelamin");
            model.addColumn("Angkatan");
            model.addColumn("Prodi");

            int rows = obj.getInt("rows");
            JSONArray results = obj.getJSONArray("results");
            mahasiswa.setDataMhs(results);
            if (rows != 0) {
                for (int i = 0; i < results.length(); i++) {
                    JSONObject item = results.getJSONObject(i);
                    model.addRow(new Object[]{
                        item.getString("mhs_nim"),
                        item.getString("mhs_nama"),
                        item.getString("mhs_jk"),
                        item.getInt("angkatan"),
                        item.getString("prodi")

                    });
                    tbMahasiswa.setModel(model);
                }
            }
            loadKelas(cProdi.getSelectedItem().toString(), Integer.parseInt(cAngkatan.getSelectedItem().toString()));
            cKelas.setVisible(true);
            cKelas.setSelectedItem("Semua");
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    void tampilSearch() {

        try {
            mahasiswa mhs = new mahasiswa();
            JSONObject obj = mhs.search();

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nim");
            model.addColumn("Nama");
            model.addColumn("Jenis Kelamin");
            model.addColumn("Angkatan");
            model.addColumn("Prodi");

            int rows = obj.getInt("rows");
            JSONArray results = obj.getJSONArray("results");
            mahasiswa.setDataMhs(results);
            if (rows != 0) {
                for (int i = 0; i < results.length(); i++) {
                    JSONObject item = results.getJSONObject(i);
                    model.addRow(new Object[]{
                        item.getString("mhs_nim"),
                        item.getString("mhs_nama"),
                        item.getString("mhs_jk"),
                        item.getInt("angkatan"),
                        item.getString("prodi")

                    });
                    tbMahasiswa.setModel(model);
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    void loadKelas(String prd, int akt) {
        try {
            Kelas ks = new Kelas();
            ks.setProdi(prd);
            ks.setAngkatan(akt);
            JSONObject obj = ks.tampilKelas();

            int rows = obj.getInt("rows");
            JSONArray results = obj.getJSONArray("results");
            mahasiswa.setDataMhs(results);
            if (rows != 0) {
                for (int i = 0; i < results.length(); i++) {
                    JSONObject item = results.getJSONObject(i);
                    String kelas = item.getString("kelas");
                    cKelas.addItem(kelas);

                }

            }
        } catch (Exception e) {
        }

    }
}
