package Main;

import Angkatan.pnAgkatan;
import Mahasiswa.pnMahasiswa;
import Prodi.pnProdi;

/**
 *
 * @author USER
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SlidePanel = new javax.swing.JPanel();
        bMhs = new javax.swing.JLabel();
        bAkt = new javax.swing.JLabel();
        bPr = new javax.swing.JLabel();
        ContenPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        SlidePanel.setBackground(new java.awt.Color(102, 204, 255));

        bMhs.setText("MAHASISWA");
        bMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMhsMouseClicked(evt);
            }
        });

        bAkt.setText("ANGKATAN");
        bAkt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAktMouseClicked(evt);
            }
        });

        bPr.setText("PRODI");
        bPr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPrMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SlidePanelLayout = new javax.swing.GroupLayout(SlidePanel);
        SlidePanel.setLayout(SlidePanelLayout);
        SlidePanelLayout.setHorizontalGroup(
            SlidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SlidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SlidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bMhs, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(bAkt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bPr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SlidePanelLayout.setVerticalGroup(
            SlidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SlidePanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(bMhs)
                .addGap(18, 18, 18)
                .addComponent(bAkt)
                .addGap(18, 18, 18)
                .addComponent(bPr)
                .addContainerGap(592, Short.MAX_VALUE))
        );

        ContenPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContenPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(SlidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SlidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ContenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(MainPanel, "card2");

        setBounds(0, 0, 1380, 775);
    }// </editor-fold>//GEN-END:initComponents

    private void bMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMhsMouseClicked
        ContenPanel.removeAll();
        ContenPanel.add(new pnMahasiswa());
        ContenPanel.revalidate();
        ContenPanel.repaint();
    }//GEN-LAST:event_bMhsMouseClicked

    private void bAktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAktMouseClicked
        ContenPanel.removeAll();
        ContenPanel.add(new pnAgkatan());
        ContenPanel.revalidate();
        ContenPanel.repaint();
    }//GEN-LAST:event_bAktMouseClicked

    private void bPrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPrMouseClicked
         ContenPanel.removeAll();
        ContenPanel.add(new pnProdi());
        ContenPanel.revalidate();
        ContenPanel.repaint();
    }//GEN-LAST:event_bPrMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel ContenPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SlidePanel;
    private javax.swing.JLabel bAkt;
    private javax.swing.JLabel bMhs;
    private javax.swing.JLabel bPr;
    // End of variables declaration//GEN-END:variables
}
