package Main;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import javax.swing.UIManager;
import java.sql.*;
import javax.swing.JOptionPane;
import User.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

public class menu extends javax.swing.JFrame {

    private static String username;

    public menu(String username) {
        initComponents();
        menu.username = username;
        tUser.setText(sesi.getNama());
        loadUserPrivileges(username);
        displayDate();
        displayTime();
        System.out.println(username);

    }

    private void loadUserPrivileges(String username) {
        try {
            User.userPrivilege up = new User.userPrivilege();
            up.setUsername(username);
            ResultSet rs = up.loadUserPrivilege();

            // Reset semua menu ke invisible
            setMenuVisibility(false);

            // Aktifkan menu berdasarkan privilege
            while (rs.next()) {
                String privilege = rs.getString("nama_privilege");
                System.out.println(privilege);
                enableMenu(privilege);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error loading privileges: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void setMenuVisibility(boolean isVisible) {

        bBukuInduk.setVisible(isVisible);
        bPembayaran.setVisible(isVisible);
        bInventaris.setVisible(isVisible);
        bManagemntsurat.setVisible(isVisible);
        bPerpustakaan.setVisible(isVisible);
        bKepegawaian.setVisible(isVisible);
        
    }

    private void enableMenu(String privilegeName) {
        switch (privilegeName) {
            case "Kepegawaian":
                bKepegawaian.setVisible(true);
                break;
            case "Buku Induk":
                bBukuInduk.setVisible(true);
                break;
            case "Pembayaran":
                bPembayaran.setVisible(true);
                break;
            case "Inventaris":
                bInventaris.setVisible(true);
                break;
            case "Manajemen Surat":
                bManagemntsurat.setVisible(true);
                break;
            case "Perpustakaan":
                bPerpustakaan.setVisible(true);
                break;
        }
    }
    private void displayDate() {
        LocalDate currentDate = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MMMM yyyy"); 
        String formattedDate = currentDate.format(formatter);
        tTanggal.setText(formattedDate);
    }

    private void displayTime() {
        LocalTime currentTime = LocalTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm"); 
        String formattedTime = currentTime.format(formatter);
        tJam.setText(formattedTime);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bUser = new javax.swing.JLabel();
        tUser = new javax.swing.JLabel();
        tTanggal = new javax.swing.JLabel();
        tJam = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bLogout = new javax.swing.JPanel();
        LOGOUT = new javax.swing.JLabel();
        LOGOUTBLU = new javax.swing.JLabel();
        bBukuInduk = new javax.swing.JButton();
        bPembayaran = new javax.swing.JButton();
        bManagemntsurat = new javax.swing.JButton();
        bPerpustakaan = new javax.swing.JButton();
        bInventaris = new javax.swing.JButton();
        bKepegawaian = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        bUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User_1.png"))); // NOI18N
        bUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bUserMouseClicked(evt);
            }
        });

        tUser.setFont(new java.awt.Font("DM Sans SemiBold", 0, 14)); // NOI18N
        tUser.setForeground(new java.awt.Color(255, 255, 255));
        tUser.setText("Admin");

        tTanggal.setBackground(new java.awt.Color(255, 255, 255));
        tTanggal.setFont(new java.awt.Font("DM Sans SemiBold", 0, 18)); // NOI18N
        tTanggal.setForeground(new java.awt.Color(255, 255, 255));
        tTanggal.setText("24 November 2024");

        tJam.setBackground(new java.awt.Color(255, 255, 255));
        tJam.setFont(new java.awt.Font("DM Sans SemiBold", 0, 12)); // NOI18N
        tJam.setForeground(new java.awt.Color(255, 255, 255));
        tJam.setText("00.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(bUser, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tUser, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 416, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tTanggal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tJam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(tUser))
                            .addComponent(bUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tJam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tTanggal)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 110, 30));

        bLogout.setBackground(new java.awt.Color(255, 255, 255));
        bLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bLogoutMouseExited(evt);
            }
        });
        bLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGOUT.setFont(new java.awt.Font("DM Sans", 1, 18)); // NOI18N
        LOGOUT.setText("Log Out");
        bLogout.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));

        LOGOUTBLU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGOUTBLU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/LOGOUT BLU.png"))); // NOI18N
        bLogout.add(LOGOUTBLU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(bLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, -1, 30));

        bBukuInduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/BUKU INDUK BLUEpng.png"))); // NOI18N
        bBukuInduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBukuIndukActionPerformed(evt);
            }
        });
        jPanel1.add(bBukuInduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 140, 150));

        bPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/PEMBAYARAN BLUE.png"))); // NOI18N
        bPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPembayaranActionPerformed(evt);
            }
        });
        jPanel1.add(bPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 140, 150));

        bManagemntsurat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/MANAJEMEN BLU.png"))); // NOI18N
        jPanel1.add(bManagemntsurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 140, 150));

        bPerpustakaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/PERPUSTAKAAN BLU.png"))); // NOI18N
        jPanel1.add(bPerpustakaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 140, 150));

        bInventaris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/IVENTARISBLU.png"))); // NOI18N
        jPanel1.add(bInventaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 140, 150));

        bKepegawaian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/KEPEGAWAIAN BLU.png"))); // NOI18N
        jPanel1.add(bKepegawaian, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 140, 150));

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMouseClicked
        dispose();
        new login.Login().setVisible(true);
    }//GEN-LAST:event_bLogoutMouseClicked

    private void bLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMouseEntered
        bLogout.setBackground(new Color(0, 0, 102));
    }//GEN-LAST:event_bLogoutMouseEntered

    private void bLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMouseExited
        bLogout.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_bLogoutMouseExited

    private void bBukuIndukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBukuIndukActionPerformed
        new menuBukuinduk().setVisible(true);
        dispose();
    }//GEN-LAST:event_bBukuIndukActionPerformed

    private void bPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPembayaranActionPerformed

    }//GEN-LAST:event_bPembayaranActionPerformed

    private void bUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bUserMouseClicked
        new popUser().setVisible(true);
        
    }//GEN-LAST:event_bUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
            UIManager.put("Button.arc", 10);
            UIManager.put("TextComponent.arc", 10);
            UIManager.put("TableHeader.background", new Color(0, 51, 153));
            UIManager.put("TableHeader.foreground", Color.WHITE);
            UIManager.put("Table.selectionBackground", new Color(102, 153, 255));
            UIManager.put("Table.alternateRowColor", new Color(240, 240, 240));
            UIManager.put("Component.focusedBorderColor", new Color(102, 153, 255));
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new menu(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JLabel LOGOUTBLU;
    private javax.swing.JButton bBukuInduk;
    private javax.swing.JButton bInventaris;
    private javax.swing.JButton bKepegawaian;
    private javax.swing.JPanel bLogout;
    private javax.swing.JButton bManagemntsurat;
    private javax.swing.JButton bPembayaran;
    private javax.swing.JButton bPerpustakaan;
    private javax.swing.JLabel bUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel tJam;
    private javax.swing.JLabel tTanggal;
    private javax.swing.JLabel tUser;
    // End of variables declaration//GEN-END:variables
}
