package Main;

import User.popUser;
import Angkatan.pnAgkatan;
import Mahasiswa.pnMahasiswa;
import Prodi.pnProdi;
import User.*;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import javax.swing.UIManager;

public class menuBukuinduk extends javax.swing.JFrame {
    private String username = sesi.getUsername();
    public menuBukuinduk() {
        initComponents();
        loadDasboard();
        
        tUser.setText(sesi.getNama());
    }

    void loadDasboard() {
        ContenPanel.removeAll();
        ContenPanel.add(new pnDasboard());
        ContenPanel.revalidate();
        ContenPanel.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SlidePanel = new javax.swing.JPanel();
        mahasiswaPanel = new javax.swing.JPanel();
        bMahasiswa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        angkatanPanel = new javax.swing.JPanel();
        bAngkatan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prodiPanel = new javax.swing.JPanel();
        bProdi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dasboardPanel = new javax.swing.JPanel();
        bDasboard = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        bLogout = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ContenPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tUser = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        SlidePanel.setBackground(new java.awt.Color(255, 255, 255));

        mahasiswaPanel.setBackground(new java.awt.Color(255, 255, 255));

        bMahasiswa.setFont(new java.awt.Font("DM Sans ExtraBold", 1, 18)); // NOI18N
        bMahasiswa.setForeground(new java.awt.Color(2, 154, 170));
        bMahasiswa.setText("Mahasiswa");
        bMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMahasiswaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bMahasiswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bMahasiswaMouseExited(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Graduation Cap_1.png"))); // NOI18N
        jLabel3.setText(" ");

        javax.swing.GroupLayout mahasiswaPanelLayout = new javax.swing.GroupLayout(mahasiswaPanel);
        mahasiswaPanel.setLayout(mahasiswaPanelLayout);
        mahasiswaPanelLayout.setHorizontalGroup(
            mahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mahasiswaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mahasiswaPanelLayout.setVerticalGroup(
            mahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mahasiswaPanelLayout.createSequentialGroup()
                .addGroup(mahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(mahasiswaPanelLayout.createSequentialGroup()
                        .addComponent(bMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(mahasiswaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        angkatanPanel.setBackground(new java.awt.Color(255, 255, 255));

        bAngkatan.setFont(new java.awt.Font("DM Sans ExtraBold", 1, 18)); // NOI18N
        bAngkatan.setForeground(new java.awt.Color(2, 154, 170));
        bAngkatan.setText("Angkatan");
        bAngkatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAngkatanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bAngkatanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bAngkatanMouseExited(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/School Backpack_1.png"))); // NOI18N

        javax.swing.GroupLayout angkatanPanelLayout = new javax.swing.GroupLayout(angkatanPanel);
        angkatanPanel.setLayout(angkatanPanelLayout);
        angkatanPanelLayout.setHorizontalGroup(
            angkatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, angkatanPanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAngkatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        angkatanPanelLayout.setVerticalGroup(
            angkatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(angkatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        prodiPanel.setBackground(new java.awt.Color(255, 255, 255));

        bProdi.setFont(new java.awt.Font("DM Sans ExtraBold", 1, 18)); // NOI18N
        bProdi.setForeground(new java.awt.Color(2, 154, 170));
        bProdi.setText("Prodi");
        bProdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bProdiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bProdiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bProdiMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/University Campus.png"))); // NOI18N

        javax.swing.GroupLayout prodiPanelLayout = new javax.swing.GroupLayout(prodiPanel);
        prodiPanel.setLayout(prodiPanelLayout);
        prodiPanelLayout.setHorizontalGroup(
            prodiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prodiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        prodiPanelLayout.setVerticalGroup(
            prodiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dasboardPanel.setBackground(new java.awt.Color(255, 255, 255));

        bDasboard.setFont(new java.awt.Font("DM Sans ExtraBold", 1, 18)); // NOI18N
        bDasboard.setForeground(new java.awt.Color(2, 154, 170));
        bDasboard.setText("Dashboard");
        bDasboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDasboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bDasboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bDasboardMouseExited(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dashboard Layout_1.png"))); // NOI18N

        javax.swing.GroupLayout dasboardPanelLayout = new javax.swing.GroupLayout(dasboardPanel);
        dasboardPanel.setLayout(dasboardPanelLayout);
        dasboardPanelLayout.setHorizontalGroup(
            dasboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dasboardPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDasboard, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dasboardPanelLayout.setVerticalGroup(
            dasboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dasboardPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(bDasboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        logoutPanel.setBackground(new java.awt.Color(255, 255, 255));

        bLogout.setFont(new java.awt.Font("DM Sans ExtraBold", 1, 18)); // NOI18N
        bLogout.setForeground(new java.awt.Color(2, 154, 170));
        bLogout.setText("Log Out");
        bLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bLogoutMouseExited(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout.png"))); // NOI18N

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutPanelLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        logoutPanelLayout.setVerticalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout SlidePanelLayout = new javax.swing.GroupLayout(SlidePanel);
        SlidePanel.setLayout(SlidePanelLayout);
        SlidePanelLayout.setHorizontalGroup(
            SlidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(angkatanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(prodiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mahasiswaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SlidePanelLayout.createSequentialGroup()
                .addComponent(dasboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SlidePanelLayout.setVerticalGroup(
            SlidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SlidePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(dasboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(mahasiswaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(angkatanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prodiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        ContenPanel.setBackground(new java.awt.Color(204, 255, 255));
        ContenPanel.setForeground(new java.awt.Color(255, 255, 255));
        ContenPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(2, 154, 170));

        tUser.setFont(new java.awt.Font("DM Sans SemiBold", 0, 14)); // NOI18N
        tUser.setForeground(new java.awt.Color(255, 255, 255));
        tUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tUser.setText("Admin");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User_1.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("DM Sans ExtraBold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BUKU INDUK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tUser, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(3, 3, 3))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(2, 131, 145));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/aaaaaa.png"))); // NOI18N
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SlidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ContenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SlidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ContenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(MainPanel, "card2");

        setBounds(0, 0, 1380, 775);
    }// </editor-fold>//GEN-END:initComponents

    private void bMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMahasiswaMouseClicked
        ContenPanel.removeAll();
        ContenPanel.add(new pnMahasiswa());
        ContenPanel.revalidate();
        ContenPanel.repaint();
    }//GEN-LAST:event_bMahasiswaMouseClicked

    private void bAngkatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAngkatanMouseClicked
        ContenPanel.removeAll();
        ContenPanel.add(new pnAgkatan());
        ContenPanel.revalidate();
        ContenPanel.repaint();
    }//GEN-LAST:event_bAngkatanMouseClicked

    private void bProdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProdiMouseClicked
        ContenPanel.removeAll();
        ContenPanel.add(new pnProdi());
        ContenPanel.revalidate();
        ContenPanel.repaint();
    }//GEN-LAST:event_bProdiMouseClicked

    private void bDasboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDasboardMouseClicked
        loadDasboard();
    }//GEN-LAST:event_bDasboardMouseClicked

    private void bDasboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDasboardMouseEntered
        dasboardPanel.setBackground(new Color(2, 131, 145));
    }//GEN-LAST:event_bDasboardMouseEntered

    private void bMahasiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMahasiswaMouseEntered
        mahasiswaPanel.setBackground(new Color(2, 131, 145));
    }//GEN-LAST:event_bMahasiswaMouseEntered

    private void bAngkatanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAngkatanMouseEntered
        angkatanPanel.setBackground(new Color(2, 131, 145));
    }//GEN-LAST:event_bAngkatanMouseEntered

    private void bProdiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProdiMouseEntered
        prodiPanel.setBackground(new Color(2, 131, 145));
    }//GEN-LAST:event_bProdiMouseEntered

    private void bMahasiswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMahasiswaMouseExited
        mahasiswaPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_bMahasiswaMouseExited

    private void bDasboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDasboardMouseExited
        dasboardPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_bDasboardMouseExited

    private void bAngkatanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAngkatanMouseExited
        angkatanPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_bAngkatanMouseExited

    private void bProdiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProdiMouseExited
        prodiPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_bProdiMouseExited

    private void bLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMouseClicked
     new menu(username).setVisible(true);
     dispose();
    }//GEN-LAST:event_bLogoutMouseClicked

    private void bLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMouseEntered
        logoutPanel.setBackground(new Color(2, 131, 145));
    }//GEN-LAST:event_bLogoutMouseEntered

    private void bLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMouseExited
        logoutPanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_bLogoutMouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new popUser().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
            UIManager.put("Button.arc", 10);
            UIManager.put("TextComponent.arc", 10);
            UIManager.put("TableHeader.background", new Color(2, 154, 170));
            UIManager.put("TableHeader.foreground", Color.WHITE);
            UIManager.put("Table.selectionBackground", new Color(2, 131, 145));
            UIManager.put("Table.alternateRowColor", new Color(240, 240, 240));
            UIManager.put("Component.focusedBorderColor", new Color(2, 154, 170));
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuBukuinduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel ContenPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SlidePanel;
    private javax.swing.JPanel angkatanPanel;
    private javax.swing.JLabel bAngkatan;
    private javax.swing.JLabel bDasboard;
    private javax.swing.JLabel bLogout;
    private javax.swing.JLabel bMahasiswa;
    private javax.swing.JLabel bProdi;
    private javax.swing.JPanel dasboardPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JPanel mahasiswaPanel;
    private javax.swing.JPanel prodiPanel;
    private javax.swing.JLabel tUser;
    // End of variables declaration//GEN-END:variables

}
